<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>m2-core-parent</artifactId>
        <groupId>io.github.sajeth</groupId>
        <version>0.0.1</version>
    </parent>

    <artifactId>m2-commons-parent</artifactId>
    <packaging>pom</packaging>
    <name>m2-commons-parent</name>

    <properties>
        <!-- https://mvnrepository.com/artifact/org.springframework.data/spring-data-relational -->
        <spring.data.relational>4.1.1</spring.data.relational>
        <!-- https://mvnrepository.com/artifact/org.springframework.data/spring-data-jpa -->
        <spring.data.jpa>4.1.1</spring.data.jpa>
        <!-- https://mvnrepository.com/artifact/org.springframework.data/spring-data-commons -->
        <spring.data.commons>4.1.1</spring.data.commons>
        <!-- https://mvnrepository.com/artifact/com.github.spotbugs/spotbugs-maven-plugin -->
        <spotbugs.plugin.version>4.10.4.1</spotbugs.plugin.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.data</groupId>
                <artifactId>spring-data-commons</artifactId>
                <version>${spring.data.commons}</version>
            </dependency>
            <dependency>
                <groupId>org.springframework.data</groupId>
                <artifactId>spring-data-relational</artifactId>
                <version>${spring.data.relational}</version>
            </dependency>
            <dependency>
                <groupId>org.springframework.data</groupId>
                <artifactId>spring-data-jpa</artifactId>
                <version>${spring.data.jpa}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-web</artifactId>
            <version>${spring.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>tools.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>${jackson.version}</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>
</project>
